server:
  port: 8080
spring:
  application:
    name: sample
  datasource:
    url: jdbc:mysql://liukewensc.mysql.rds.aliyuncs.com:3306/dev_framework_demo
    username: kewen
    password: Lh19921002
    driver-class-name: com.kewen.framework.boot.basic.p6spy.KP6SpyDriver
    hikari:
      auto-commit:true
      connection-test-query:select 1
      connection-timeout:30000
      idle-timeout:600000
      max-lifetime:1800000
      maximum-pool-size:5
      minimum-idle:2
      validation-timeout:5000
      pool-name:HikaraPool-1
kewen:
  message:
    fang-tang:
      key: SCT248328TA-iYbvN5Vab4ixXBUOqA60fLY5
      domain: https://sctapi.ftqq.com
  request:
    message:
      fang-tang: true
    persistent:
      database: true