kewen:
  message:
    fang-tang:
      key: ''
      domain: ''
  request:
    persistent:
      database: true
    message:
      fang-tang: true
  tenant:
    open: false
  security:
    session:
      maximum-sessions: 10 #最大session数量
      maxSessions-prevents-login: false # 到了最大session是阻止还是过期最久的
    remember-me:
      enabled: true #是否开启记住我
      remember-parameter: remember-me #记住我的key
      validity-seconds: 2592000  #记住时间，单位秒，默认30天
