server:
  port: 8081
spring:
  application:
    name: sample
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/kewen_framework_auth_template
    username: open_framework
    password: Framework123456_
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit:true
      connection-test-query:select 1
      connection-timeout:30000
      idle-timeout:600000
      max-lifetime:1800000
      maximum-pool-size:5
      minimum-idle:2
      validation-timeout:5000
      pool-name:HikaraPool-1
  session:
    store-type: jdbc
    timeout: 2D #超时2天

logging:
  level:
    org.springframework.security: debug
  file:
    name: auth-sample
    path: ./logs

kewen:
  auth:
    auth-data-table:
      table-name: sys_auth_data
      id-column: id
      data-id-column: data_id
      authority-column: authority
      description-column: description
      business-function-column: business_function
      operate-column: operate
    cache-auth: false  # 是否缓存菜单权限
  security:
    remember-me:
      enabled: true
      remember-parameter: remember-me
      validity-seconds: 2592000
    session:
      maximum-sessions: 10               #最大session数量
      max-sessions-prevents-login: true # 是否不允许挤下线
    current-user-url: /currentUser    #当前用户接口地址
    login:
      password:
        login-url: /login                 #登录地址
        username-parameter: username      # username参数
        password-parameter: password      # password参数
      saml:
        registrations:
          -
            registration-id: idp4-test-kewen-loc-registration          # relying party registration id
            sp-entity-id: idp4-test-kewen-loc     # your app entity id
            #use-metadata: true
            #web-sso-url: "https://idp4-test.alibaba.net/sso/saml" # your idp sso url
            #idp-certificate-resource: classpath:saml/idp-certificate.crt # your idp certificate resource
            metadata-resource: classpath:saml/metadata/idaas-idp4-test-metadata.xml